version: '3.8'
services:
  backend:
    image: ${DOCKERHUB_USERNAME}/backend
    build: ./backend
    command: ["gunicorn", "backend.wsgi:application", "--bind", "0.0.0.0:8000"]
    ports:
      - 8000:8000

  frontend:
    image: ${DOCKERHUB_USERNAME}/frontend
    build: ./frontend
    command: ["serve", "-s", "build", "-l", "3000"]
    ports:
      - 3000:3000