version: '3.8'
services:
  backend:
    image: ${DOCKERHUB_USERNAME}/backend
    build: ./backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000

  frontend:
    image: ${DOCKERHUB_USERNAME}/frontend
    build: ./frontend
    command: serve -s build -l 3000
    ports:
      - 3000:3000

  nginx:
    image: ${DOCKERHUB_USERNAME}/nginx
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/letsencrypt
    depends_on:
      - backend
      - frontend
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}

  certbot:
    image: certbot/dns-cloudflare:v1.8.0
    command: certonly --non-interactive --dns-cloudflare --dns-cloudflare-credentials /etc/letsencrypt/cloudflare.ini --agree-tos -d ${DOMAIN_NAME} -d "*.${DOMAIN_NAME}" --dns-cloudflare-propagation-seconds 60 -m ${CLOUDFLARE_EMAIL}
    volumes:
      - certs:/etc/letsencrypt
      - ./certbot/cloudflare.ini:/etc/letsencrypt/cloudflare.ini
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL} 

volumes:
  certs:
  static_volume: